version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lms_postgres
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./server
    container_name: lms_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    networks:
      - lms_network
    command: ["npm", "run", "dev"]

  frontend:
    build: ./client
    container_name: lms_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - lms_network
    env_file:
      - ./client/.env.local

networks:
  lms_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
